# Generated by Django 4.0.6 on 2022-07-30 05:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('year', models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2022', max_length=256, verbose_name='коллекция')),
                ('image', models.ImageField(upload_to='media/products/%Y/%m/%d')),
                ('image2', models.ImageField(null=True, upload_to='media/products/%Y/%m/%d')),
                ('image3', models.ImageField(null=True, upload_to='media/products/%Y/%m/%d')),
                ('size', models.CharField(choices=[('36', 'S'), ('38', 'M'), ('40', 'L'), ('42', 'XL')], default='S', max_length=256, verbose_name='размер')),
                ('length', models.CharField(choices=[('длинная', 'длинная'), ('короткая', 'короткая'), ('средний', 'средний')], default='длинная', max_length=256, verbose_name='длина')),
                ('length_hand', models.CharField(choices=[('длинная', 'длинная'), ('короткая', 'короткая'), ('средний', 'средний'), ('нет', 'нет')], default='короткая', max_length=256, verbose_name='длина рукава')),
                ('image_thumbnail', imagekit.models.fields.ProcessedImageField(null=True, upload_to='media/products/%Y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Одежда',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
