# Generated by Django 4.0.6 on 2022-07-30 06:41

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', imagekit.models.fields.ProcessedImageField(null=True, upload_to='media/products/%Y/%m/%d')),
            ],
        ),
    ]
