# Generated by Django 4.0.6 on 2022-07-30 06:50

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bannerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='images',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='media/banner'),
        ),
    ]
