# Generated by Django 4.0.6 on 2022-07-30 07:16

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_bannerimage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='images',
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(null=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(null=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
