# Generated by Django 4.0.6 on 2022-07-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_bannerimage_images_bannerimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='S', max_length=4)),
            ],
            options={
                'verbose_name': 'размер',
            },
        ),
        migrations.AlterModelOptions(
            name='bannerimage',
            options={'verbose_name': 'Изображение баннера', 'verbose_name_plural': 'Изображения баннеров'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='products.size'),
        ),
    ]
